// yuigrammars.js — 組み込み構文 JSON をインライン化した辞書
//
// **自動生成ファイル** — 直接編集しないこと。
// syntax/*.json を更新したあと `node scripts/build-grammars.js` を実行して再生成する。
//
// Web アプリ埋め込み時に fs アクセスを避けるため、すべての組み込み grammar を
// 1 つの JS モジュールにインラインで持つ。外部 URL の grammar は
// `loadSyntaxFromUrl(url)` で非同期ロードする (yuisyntax.js 参照)。

/** 組み込み grammar 辞書 ({name: terminals}) */
export const GRAMMARS = Object.freeze({
  "ast": {
    "syntax": "ASTNode",
    "whitespace": "[ \\t\\r　]",
    "whitespaces": "[ \\t\\r　]+",
    "linefeed": "[\\n]",
    "word-segmenter": " ",
    "line-comment-begin": "\\#",
    "comment-begin": "",
    "comment-end": "",
    "statement-separator": ",",
    "number-begin": "NumberNode\\(",
    "number-first-char": "[0-9]",
    "number-chars": "[0-9]*",
    "number-dot-char": "[\\.]",
    "number-end": "\\)",
    "name-begin": "NameNode\\(\"",
    "name-first-char": "[A-Za-z_]",
    "name-chars": "[A-Za-z0-9_]*",
    "name-end": "\"\\)",
    "string-begin": "StringNode\\(\"",
    "string-end": "\"\\)",
    "string-escape": "\\\\",
    "string-interpolation-begin": "\\{",
    "string-interpolation-end": "\\}",
    "string-content-end": "\\\\|\\{|\\\"",
    "array-begin": "ArrayNode\\(\\[",
    "array-end": "\\]\\)",
    "array-separator": ",",
    "object-begin": "ObjectNode\\(\\[",
    "object-end": "\\]\\)",
    "object-separator": ",",
    "key-value-separator": ",",
    "grouping-begin!": "\\(",
    "grouping-end!": "\\)",
    "length-begin": "ArrayLenNode\\(",
    "length-end": "\\)",
    "minus-begin": "MinusNode\\(",
    "minus-end": "\\)",
    "array-indexer-begin": "GetIndexNode\\(",
    "array-indexer-suffix": ",",
    "array-indexer-end": "\\)",
    "funcapp-begin": "FuncApp\\(",
    "funcapp-args-begin": "",
    "funcapp-args-end": "\\)",
    "funcapp-separator": ",",
    "block-begin": "BlockNode\\(\\[",
    "block-end": "\\]\\)",
    "block-separator": ",",
    "assignment-begin": "AssignmentNode\\(",
    "assignment-infix": ",",
    "assignment-end": "\\)",
    "increment-begin": "IncrementNode\\(",
    "increment-end": "\\)",
    "decrement-begin": "DecrementNode\\(",
    "decrement-end": "\\)",
    "append-begin": "AppendNode\\(",
    "append-infix": ",",
    "append-end": "\\)",
    "print-begin": "PrintExpression\\(",
    "print-end": "\\)",
    "break": "BreakNode\\(\\)",
    "pass": "PassNode\\(\\)",
    "return-begin": "ReturnNode\\(",
    "return-end": "\\)",
    "repeat-begin": "RepeatNode\\(",
    "repeat-times": ",",
    "repeat-block": "",
    "repeat-end": "\\)",
    "if-begin": "IfNode\\(",
    "if-condition-begin": "",
    "if-condition-end": "",
    "if-prefix": "",
    "if-infix==": ", \"==\",",
    "if-infix!=": ", \"!=\",",
    "if-infix<": ", \"<\",",
    "if-infix<=": ", \"<=\",",
    "if-infix>": ", \">\",",
    "if-infix>=": ", \">=\",",
    "if-infixin": ", \"in\",",
    "if-infixnotin": ", \"notin\",",
    "if-then": ",",
    "if-else": ",",
    "if-end": "\\)",
    "funcdef-begin": "FuncNode\\(",
    "funcdef-name-begin": "",
    "funcdef-name-end": "",
    "funcdef-args-begin": ", \\[",
    "funcdef-noarg": "\\[\\]",
    "funcdef-arg-separator": "\\,",
    "funcdef-args-end": "\\]",
    "funcdef-block": ",",
    "funcdef-end": "\\)",
    "assert-begin": "AssertNode\\(",
    "assert-infix": ",",
    "assert-end": "\\)",
    "import-begin": "ImportNode\\(",
    "import-end": "\\)"
  },
  "bridget": {
    "syntax": "Plain English",
    "function-language": "en",
    "whitespace": "[ \\t\\r　]",
    "whitespaces": "[ \\t\\r　]+",
    "linefeed": "[\\n]",
    "line-comment-begin": "#",
    "word-segmenter": " ",
    "comment-begin": "",
    "comment-end": "",
    "indent": "  ",
    "special-name-pattern": "[^\\s\\[\\]\\(\\)\",\\+\\-\\*\\/\\%\\=\\!\\<\\>]+",
    "special-name-funcname": "\\s(?:is|to)\\s+({name_pattern})\\s+of",
    "special-name-variable": "Remember\\s+that\\s+({name_pattern})\\s+is",
    "null": "[nN]othing|null",
    "boolean-true": "[yY]es|true",
    "boolean-false": "[nN]o|false",
    "number-first-char": "[0-9]",
    "number-chars": "[0-9]*",
    "number-dot-char": "[\\.]",
    "name-first-char": "[A-Za-z_]",
    "name-chars": "[A-Za-z0-9_]*",
    "extra-name-begin": "`",
    "extra-name-end": "`",
    "string-begin": "\"",
    "string-end": "\"",
    "string-escape": "\\\\",
    "string-interpolation-begin": "\\{",
    "string-interpolation-end": "\\}",
    "string-content-end": "\\\\|\\{|\\\"",
    "binary-infix+": "\\+",
    "binary-infix-": "-",
    "binary-infix*": "\\*",
    "binary-infix/": "/",
    "binary-infix%": "%",
    "binary-infix==": "==",
    "binary-infix!=": "!=",
    "binary-infix<=": "<=",
    "binary-infix>=": ">=",
    "binary-infix<": "<",
    "binary-infix>": ">",
    "unary-minus": "-",
    "array-indexer-begin": "item",
    "array-indexer-infix": "in",
    "array-indexer-suffix": "",
    "array-indexer-end": "",
    "array-indexer-order": "reversed",
    "property-length": "'s\\s+length",
    "funcapp-args-begin": "of",
    "funcapp-args-end": "",
    "funcapp-separator": "and",
    "funcapp-noarg": ", do it",
    "import-standard": "Use the standard library",
    "import-begin": "Use",
    "import-end": "",
    "block-begin": ":",
    "block-end": "",
    "assignment-begin": "Remember\\s+that",
    "assignment-infix": "is",
    "assignment-end": "",
    "increment-begin": "Increase",
    "increment-end": "(by\\s+1)?",
    "decrement-begin": "Decrease",
    "decrement-end": "(by\\s+1)?",
    "append-begin": "Add",
    "append-infix": "to",
    "append-end": "",
    "append-order": "reverse",
    "!break": "break",
    "break": "Leave the loop",
    "pass": "Do nothing",
    "print-begin": "Now,",
    "print-end": "",
    "!return-begin": "return",
    "return-begin": "The answer is",
    "return-end": "",
    "return-none": "Stop here",
    "repeat-begin": "Do this",
    "repeat-times": "times",
    "repeat-block": "",
    "repeat-end": "End do",
    "!if-begin": "if",
    "if-begin": "When",
    "if-condition-begin": "",
    "if-condition-end": "",
    "if-prefix": "",
    "if-infix==": "is\\s",
    "if-infix!=": "is not\\s",
    "if-infix<": "is less than",
    "if-infix<=": "is at least",
    "if-infix>": "is more than",
    "if-infix>=": "is at most",
    "if-infixin": "is in\\s",
    "if-infixnotin": "is not in",
    "if-then": ",\\s+then",
    "if-else": "But,\\s+if not",
    "if-end": "End when",
    "funcdef-begin": "This is how to",
    "funcdef-name-begin": "",
    "funcdef-name-end": "",
    "funcdef-args-begin": "of",
    "funcdef-arg-separator": "and",
    "funcdef-args-end": "",
    "funcdef-noarg": "[^o][^f]",
    "funcdef-block": "",
    "funcdef-end": "Now you know"
  },
  "emoji": {
    "syntax": "🪢",
    "function-language": "emoji",
    "whitespace": "[ \\t\\r　]",
    "whitespaces": "[ \\t\\r　]+",
    "word-segmenter": " ",
    "linefeed": "[\\n]",
    "line-comment-begin": "💭|🗨️|📌|⚠️",
    "indent": "  ",
    "comment-begin": "",
    "comment-end": "",
    "special-name-pattern": "[^\\s\\[\\]\\(\\)\",\\+\\-\\*\\/\\%\\=\\!\\<\\>]+",
    "special-name-variable": "({name_pattern})\\s+⬅️",
    "number-first-char": "[0-9]",
    "number-chars": "[0-9]*",
    "number-dot-char": "[\\.]",
    "null": "🫥|null",
    "boolean-true": "👍|true",
    "boolean-false": "👎|false",
    "name-first-char": "[A-Za-z_]",
    "name-chars": "[A-Za-z0-9_]*",
    "extra-name-begin": "",
    "extra-name-end": "",
    "string-begin": "\"",
    "string-end": "\"",
    "string-escape": "\\\\",
    "string-interpolation-begin": "\\{",
    "string-interpolation-end": "\\}",
    "string-content-end": "\\\\|\\{|\\\"",
    "array-begin": "\\[",
    "array-end": "\\]",
    "array-separator": ",",
    "object-begin": "\\{",
    "object-end": "\\}",
    "object-separator": ",",
    "key-value-separator": ":",
    "grouping-begin": "\\(",
    "grouping-end": "\\)",
    "unary-minus": "-",
    "unary-length": "📐",
    "binary-infix+": "➕|\\+|＋",
    "binary-infix-": "➖|\\-|－",
    "binary-infix*": "✖️|\\*|×",
    "binary-infix/": "➗|/|÷",
    "binary-infix%": "💔|%|％",
    "binary-infix==": "⚖️|==",
    "binary-infix!=": "🚫⚖️|!=",
    "binary-infix<=": "📈⚖️|<=",
    "binary-infix>=": "📉⚖️|>=",
    "binary-infix<": "📈|<",
    "binary-infix>": "📉|>",
    "binary-infixin": "📥|∈",
    "binary-infixnotin": "🚫📥|∉",
    "array-indexer-suffix": "\\[",
    "array-indexer-end": "\\]",
    "property-accessor": "",
    "property-type": "",
    "not-property-name": "",
    "funcapp-args-begin": "\\(",
    "funcapp-args-end": "\\)",
    "funcapp-separator": ",",
    "block-begin": "👉",
    "block-end": "🔚",
    "assignment-begin": "",
    "assignment-infix": "⬅️",
    "assignment-end": "",
    "increment-begin": "",
    "increment-end": "⬆️",
    "decrement-begin": "",
    "decrement-end": "⬇️",
    "append-begin": "",
    "append-infix": "🧲",
    "append-end": "",
    "print-begin": "",
    "print-end": "",
    "break": "🚀",
    "pass": "💤",
    "return-begin": "✅|💡",
    "return-end": "",
    "repeat-begin": "🌀",
    "repeat-times": "",
    "repeat-block": "",
    "repeat-end": "",
    "if-begin": "❓|🤔",
    "if-condition-begin": "",
    "if-condition-end": "",
    "if-prefix": "",
    "if-infix==": "⚖️|==|＝",
    "if-infix!=": "🚫⚖️|!=|≠",
    "if-infix<": "📈|<",
    "if-infix<=": "📈⚖️|<=|≦",
    "if-infix>": "📉|>",
    "if-infix>=": "📉⚖️|>=|≧",
    "if-infixin": "📥|∈",
    "if-infixnotin": "🚫📥|∉",
    "if-then": "",
    "else-if": "❗❓",
    "if-else": "❗|🙅",
    "if-end": "",
    "funcdef-begin": "🧩",
    "funcdef-name-begin": "",
    "funcdef-name-end": "",
    "funcdef-args-begin": "\\(",
    "funcdef-arg-separator": "\\,",
    "funcdef-args-end": "\\)",
    "funcdef-noarg": "",
    "funcdef-block": "",
    "funcdef-end": "",
    "import-standard": "🗝️\\s+📚",
    "import-begin": "🗝️",
    "import-end": ""
  },
  "empty": {
    "syntax": "empty"
  },
  "jslike": {
    "syntax": "javascript-like",
    "function-language": "en",
    "whitespace": "[ \\t\\r　]",
    "whitespaces": "[ \\t\\r　]+",
    "linefeed": "[\\n]",
    "word-segmenter": " ",
    "line-comment-begin": "//",
    "comment-begin": "/\\*",
    "comment-end": "\\*/",
    "keywords": "function|return|if|else|for|in|not|and|or|break|assert",
    "statement-separator": ";",
    "null": "null",
    "boolean-true": "true",
    "boolean-false": "false",
    "!string-begin": "'|`",
    "grouping-begin": "\\(",
    "grouping-end": "\\)",
    "binary-infix+": "\\+",
    "binary-infix-": "\\-",
    "binary-infix*": "\\*",
    "binary-infix/": "\\/",
    "binary-infix%": "\\%",
    "binary-infix==": "==",
    "binary-infix!=": "!=",
    "binary-infix<=": "<=",
    "binary-infix>=": ">=",
    "binary-infix<": "<",
    "binary-infix>": ">",
    "unary-minus": "\\-",
    "array-indexer-suffix": "\\[",
    "array-indexer-end": "\\]",
    "property-length": "\\.length",
    "not-property-name": "push",
    "funcapp-args-begin": "\\(",
    "funcapp-args-end": "\\)",
    "funcapp-separator": ",",
    "block-begin-prefix": " ",
    "block-begin": "\\{",
    "block-end": "\\}",
    "assignment-begin": "",
    "assignment-infix": "\\=",
    "assignment-end": "",
    "increment-begin": "",
    "increment-end": "\\+\\+|\\+\\=\\s*1",
    "decrement-begin": "",
    "decrement-end": "\\-\\-|\\-\\=\\s*1",
    "append-begin": "",
    "append-infix": ".push\\s*\\(",
    "append-end": "\\)",
    "import-begin": "require\\s*\\(",
    "import-end": "\\)",
    "import-standard": "require\\s*\\(\"stdlib\"\\)",
    "print-begin": "",
    "print-end": "",
    "break": "break",
    "pass": "",
    "return-begin": "return\\s",
    "return-end": "",
    "return-noarg": "return",
    "repeat-begin": "while\\s*\\(\\s+times\\s*\\(",
    "repeat-times": "\\)\\s*\\)",
    "repeat-block": "",
    "repeat-end": "",
    "if-begin": "if\\s",
    "if-condition-begin": "\\(",
    "if-condition-end": "\\)",
    "if-prefix": "",
    "if-infix==": "==",
    "if-infix!=": "!=",
    "if-infix<": "<",
    "if-infix<=": "<=",
    "if-infix>": ">",
    "if-infix>=": ">=",
    "if-infixin": "in",
    "if-then": "",
    "if-else": "else\\s*",
    "if-end": "",
    "funcdef-begin": "function\\s",
    "funcdef-name-begin": "",
    "funcdef-name-end": "",
    "funcdef-args-begin": "\\(",
    "funcdef-noarg": "",
    "funcdef-arg-separator": ",",
    "funcdef-args-end": "\\)",
    "funcdef-block": "",
    "funcdef-end": ""
  },
  "nannan": {
    "syntax": "なんなん？",
    "function-language": "ja",
    "whitespace": "[ \\t\\r　]",
    "whitespaces": "[ \\t\\r　]+",
    "linefeed": "[\\n]",
    "line-comment-begin": "⚠️",
    "comment-begin": "",
    "comment-end": "",
    "indent": "  ",
    "keywords": "def|return|if|else|elif|for|in|not|and|or|break|pass|assert|import|True|False|None",
    "null": "「しらんがな」|null",
    "boolean-true": "「そやな」|true",
    "boolean-false": "「ちゃうな」|false",
    "grouping-begin!": "\\(",
    "grouping-end!": "\\)",
    "length-begin": "\\|",
    "length-end": "\\|",
    "binary-infix+": "\\+|＋",
    "binary-infix-": "-|ー",
    "binary-infix*": "\\*|×",
    "binary-infix/": "/|÷",
    "binary-infix%": "%|％",
    "binary-infix==": "==|＝＝",
    "binary-infix!=": "!=|≠",
    "binary-infix<=": "<=|≦",
    "binary-infix>=": ">=|≧",
    "binary-infix<": "<|＜",
    "binary-infix>": ">|＞",
    "binary-infixin": "∈",
    "binary-infixnotin": "∉",
    "unary-minus": "-",
    "array-indexer-suffix": "\\[",
    "array-indexer-end": "\\]",
    "property-length": "の大きさ",
    "funcapp-args-begin": "\\(",
    "funcapp-args-end": "\\)",
    "funcapp-separator": ",",
    "import-standard": "標準のやつ使う",
    "import-begin": "",
    "import-end": "を使う",
    "block-begin": "？|❓",
    "block-end": "",
    "block-line": "",
    "assignment-begin": "",
    "assignment-infix": "=",
    "assignment-end": "",
    "increment-begin": "",
    "increment-infix": "",
    "increment-end": "上げとく",
    "increment-lookahead": "上げとく",
    "decrement-begin": "",
    "decrement-infix": "",
    "decrement-end": "下げとく",
    "decrement-lookahead": "下げとく",
    "append-begin": "",
    "append-infix": "に",
    "append-end": "を?入れとく",
    "print-begin": "",
    "print-end": "",
    "break": "もうええって",
    "pass": "ほっとく",
    "return-begin": "この",
    "return-end": "だよ",
    "return-none": "わからん",
    "repeat-begin": "",
    "repeat-times": "回[、]?",
    "repeat-block": "まわそうか",
    "repeat-end": "",
    "if-lookahead": "ほんま",
    "if-begin": "",
    "if-condition-begin": "",
    "if-condition-end": "",
    "if-prefix": "",
    "if-infix": "が",
    "if-suffix==": "と同じ",
    "if-suffix!=": "やない",
    "if-suffix<": "より小さい",
    "if-suffix<=": "以下",
    "if-suffix>": "より大きい",
    "if-suffix>=": "以上",
    "if-suffixin": "のいずれか",
    "if-suffixnotin": "のいずれでもない",
    "if-then": "ってほんま",
    "if-else": "違うん",
    "if-end": "",
    "funcdef-lookahead": "なんなん",
    "funcdef-begin": "",
    "funcdef-name-begin": "",
    "funcdef-name-end": "",
    "funcdef-args-begin": "\\(",
    "funcdef-arg-separator": "[,、]",
    "funcdef-args-end": "\\)",
    "funcdef-block": "ってなんなん",
    "funcdef-end": "",
    "assert-begin": ">>>\\s+",
    "assert-infix": "[\\n]",
    "assert-end": ""
  },
  "pylike": {
    "syntax": "python-like",
    "function-language": "en",
    "whitespace": "[ \\t\\r　]",
    "whitespaces": "[ \\t\\r　]+",
    "linefeed": "[\\n]",
    "word-segmenter": " ",
    "line-comment-begin": "[#＃]",
    "comment-begin": "",
    "comment-end": "",
    "indent": "  ",
    "keywords": "def|return|if|else|elif|for|in|not|and|or|break|pass|assert|import|True|False|None",
    "null": "None",
    "boolean-true": "True",
    "boolean-false": "False",
    "number-first-char": "[0-9]",
    "number-chars": "[0-9]*",
    "number-dot-char": "[\\.]",
    "name-first-char": "[A-Za-z_]",
    "name-chars": "[A-Za-z0-9_]*",
    "extra-name-begin": "",
    "extra-name-end": "",
    "string-begin": "\"",
    "string-end": "\"",
    "string-escape": "\\\\",
    "string-interpolation-begin": "\\{",
    "string-interpolation-end": "\\}",
    "string-content-end": "\\\\|\\{|\\\"",
    "array-begin": "\\[",
    "array-end": "\\]",
    "array-separator": ",",
    "object-begin": "\\{",
    "object-end": "\\}",
    "object-separator": ",",
    "key-value-separator": ":",
    "grouping-begin": "\\(",
    "grouping-end": "\\)",
    "length-begin": "len\\s*\\(",
    "length-end": "\\)",
    "binary-infix+": "\\+",
    "binary-infix-": "\\-",
    "binary-infix*": "\\*",
    "binary-infix/": "\\/",
    "binary-infix%": "\\%",
    "binary-infix==": "==",
    "binary-infix!=": "!=",
    "binary-infix<=": "<=",
    "binary-infix>=": ">=",
    "binary-infix<": "<",
    "binary-infix>": ">",
    "unary-minus": "\\-",
    "array-indexer-suffix": "\\[",
    "array-indexer-end": "\\]",
    "property-accessor": "\\.",
    "not-property-name": "append",
    "funcapp-args-begin": "\\(",
    "funcapp-args-end": "\\)",
    "funcapp-separator": ",",
    "block-begin": "\\:",
    "block-end": "",
    "block-else": "else|elif|except|finally",
    "block-line": "",
    "assignment-begin": "",
    "assignment-infix": "\\=",
    "assignment-end": "",
    "increment-begin": "",
    "increment-end": "\\+\\=\\s*1",
    "decrement-begin": "",
    "decrement-end": "\\-\\=\\s*1",
    "append-begin": "",
    "append-infix": ".append\\s*\\(",
    "append-end": "\\)",
    "print-begin": "",
    "print-end": "",
    "break": "break",
    "pass": "pass",
    "return-begin": "return\\s",
    "return-end": "",
    "repeat-begin": "while\\s+times\\s*\\(",
    "repeat-times": "\\)",
    "repeat-block": "",
    "repeat-end": "",
    "if-begin": "if\\s",
    "if-condition-begin": "",
    "if-condition-end": "",
    "if-prefix": "",
    "if-infix==": "==",
    "if-infix!=": "!=",
    "if-infix<": "<",
    "if-infix<=": "<=",
    "if-infix>": ">",
    "if-infix>=": ">=",
    "if-infixin": "in\\s",
    "if-infixnotin": "not\\s+in\\s",
    "if-then": "",
    "if-else": "else\\s*",
    "if-end": "",
    "funcdef-begin": "def\\s",
    "funcdef-name-begin": "",
    "funcdef-name-end": "",
    "funcdef-args-begin": "\\(",
    "funcdef-noarg": "",
    "funcdef-arg-separator": ",",
    "funcdef-args-end": "\\)",
    "funcdef-block": "",
    "funcdef-end": "",
    "import-standard": "import\\s+stdlib",
    "import-begin": "import\\s",
    "import-end": ""
  },
  "sexpr": {
    "syntax": "s-expression",
    "function-language": "en",
    "whitespace": "[ \\t\\r\\n　]",
    "whitespaces": "[ \\t\\r\\n　]+",
    "linefeed": "[\\n]",
    "line-comment-begin": ";",
    "comment-begin": "",
    "comment-end": "",
    "word-segmenter": " ",
    "indent": "",
    "keywords": "begin\\b|require\\b|inc\\b|dec\\b|append\\b|set\\b|aref\\b|if\\b|repeat\\b|break\\b|print\\b|assert\\b|define\\b|return\\b",
    "special-name-pattern": "[^\\s\\[\\]\\(\\)\",]+",
    "special-name-funcname": "\\(({name_pattern})\\s",
    "special-name-variable": "\\(set\\!\\s+({name_pattern})\\s",
    "null": "nil|null",
    "boolean-true": "true",
    "boolean-false": "false",
    "number-first-char": "[0-9]",
    "number-chars": "[0-9]*",
    "number-dot-char": "[\\.]",
    "name-first-char": "[A-Za-z_]",
    "name-chars": "[A-Za-z0-9_\\!\\?]*",
    "string-begin": "\"",
    "string-end": "\"",
    "string-escape": "\\\\",
    "string-interpolation-begin": "\\{",
    "string-interpolation-end": "\\}",
    "string-content-end": "\\\\|\\{|\\\"",
    "!string-begin": "'|f\"",
    "array-begin": "\\[",
    "array-end": "\\]",
    "array-separator": ",",
    "object-begin": "\\{",
    "object-end": "\\}",
    "object-separator": ",",
    "key-value-separator": ":",
    "grouping-begin": "",
    "grouping-end": "",
    "unary-minus": "",
    "minus-begin": "\\(-\\s+",
    "minus-end": "\\)",
    "length-begin": "\\(len\\s+",
    "length-end": "\\)",
    "binary-infix-prefix-begin": "\\(",
    "binary-infix-prefix+": "\\+",
    "binary-infix-prefix-": "-",
    "binary-infix-prefix*": "\\*",
    "binary-infix-prefix/": "/",
    "binary-infix-prefix%": "%",
    "binary-infix-prefix==": "==",
    "binary-infix-prefix!=": "!=",
    "binary-infix-prefix<=": "<=",
    "binary-infix-prefix>=": ">=",
    "binary-infix-prefix<": "<",
    "binary-infix-prefix>": ">",
    "binary-infix-prefix-end": "\\)",
    "array-indexer-begin": "\\(aref\\s+",
    "array-indexer-suffix": "",
    "array-indexer-end": "\\)",
    "funcapp-begin": "\\(",
    "funcapp-args-begin": "",
    "funcapp-args-end": "",
    "funcapp-separator": "",
    "funcapp-end": "\\)",
    "import-standard": "\\(require-standard\\)",
    "import-begin": "\\(require\\s+",
    "import-end": "\\)",
    "block-begin-prefix": " ",
    "block-begin": "\\(begin\\s+",
    "block-end": "\\)",
    "assignment-begin": "\\(set\\!\\s+",
    "assignment-infix": "",
    "assignment-end": "\\)",
    "increment-begin": "\\(inc\\!\\s+",
    "increment-end": "\\)",
    "decrement-begin": "\\(dec\\!\\s+",
    "decrement-end": "\\)",
    "append-begin": "\\(append\\s+",
    "append-infix": "",
    "append-end": "\\)",
    "#print-begin": "\\(print\\s+",
    "#print-end": "\\)",
    "break": "\\(break\\)",
    "pass": "",
    "return-begin": "\\(return\\s+",
    "return-end": "\\)",
    "return-none": "\\(return\\)",
    "repeat-begin": "\\(repeat\\s+",
    "repeat-times": "",
    "repeat-end": "\\)",
    "if-begin": "\\(if\\s+",
    "if-condition-begin": "\\(",
    "if-condition-end": "\\)",
    "if-prefix==": "==",
    "if-prefix!=": "!=",
    "if-prefix<": "<",
    "if-prefix<=": "<=",
    "if-prefix>": ">",
    "if-prefix>=": ">=",
    "if-prefixin": "in",
    "if-prefixnotin": "not-in",
    "if-then": "",
    "if-else": "",
    "if-end": "\\)",
    "funcdef-begin": "\\(define\\s+",
    "funcdef-name-begin": "\\(",
    "funcdef-name-end": "",
    "funcdef-args-begin": "",
    "funcdef-arg-separator": "",
    "funcdef-args-end": "\\)",
    "funcdef-noarg": "",
    "funcdef-block": "",
    "funcdef-end": "\\)",
    "assert-begin": "\\(assert\\s+",
    "assert-infix": "",
    "assert-end": "\\)"
  },
  "wenyan": {
    "syntax": "Wenyan Like",
    "whitespace": "[ \\t\\r　]",
    "whitespaces": "[ \\t\\r　]+",
    "linefeed": "[\\n]",
    "line-comment-begin": "注(、|。)?",
    "word-segmenter": "",
    "comment-begin": "注始(。|)",
    "comment-end": "注終(。|)",
    "indent": "  ",
    "special-name-pattern": "[^\\s\\[\\]\\(\\)\",\\+\\-\\*\\/\\%\\=\\!\\<\\>]+",
    "special-name-funcname": "施\\s*({name_pattern})\\s*於",
    "special-name-variable": "名之曰\\s*({name_pattern})\\s*[。]",
    "null": "無|null",
    "boolean-true": "然|true",
    "boolean-false": "否|false",
    "number-first-char": "[0-9]",
    "number-chars": "[0-9]*",
    "number-dot-char": "[\\.]",
    "name-first-char": "[A-Za-z_]",
    "name-chars": "[A-Za-z0-9_]*",
    "extra-name-begin": "`",
    "extra-name-end": "`",
    "string-begin": "「",
    "string-end": "」",
    "string-escape": "\\\\",
    "string-interpolation-begin": "\\{",
    "string-interpolation-end": "\\}",
    "binary-infix+": "\\+",
    "binary-infix-": "-",
    "binary-infix*": "\\*",
    "binary-infix/": "/",
    "binary-infix%": "%",
    "binary-infix==": "==",
    "binary-infix!=": "!=",
    "binary-infix<=": "<=",
    "binary-infix>=": ">=",
    "binary-infix<": "<",
    "binary-infix>": ">",
    "unary-minus": "-",
    "array-indexer-begin": "取",
    "array-indexer-infix": "之第",
    "array-indexer-suffix": "",
    "array-indexer-end": "",
    "property-length": "之量",
    "funcapp-begin": "施",
    "funcapp-args-begin": "於",
    "funcapp-args-end": "",
    "funcapp-separator": "與",
    "funcapp-noarg": "以虛",
    "import-standard": "引標準庫",
    "import-begin": "引",
    "import-end": "",
    "block-begin": "",
    "block-end": "",
    "assignment-begin": "吾有一數(、|)曰",
    "assignment-infix": "(、|)名之曰",
    "assignment-end": "。",
    "assignment-order": "reversed",
    "increment-begin": "(增|増)",
    "increment-end": "以一(。|)",
    "decrement-begin": "減",
    "decrement-end": "以一(。|)",
    "append-begin": "納",
    "append-infix": "入",
    "append-end": "(。|)",
    "append-order": "reversed",
    "!break": "break",
    "break": "止(。|)",
    "pass": "無為(。|)",
    "print-begin": "吿曰",
    "print-end": "(。|)",
    "!return-begin": "return",
    "return-begin": "以",
    "return-end": "答(。|)",
    "return-none": "還無(。|)",
    "repeat-begin": "",
    "repeat-times": "度、",
    "repeat-block": "",
    "repeat-end": "度畢(。|)",
    "!if-begin": "if",
    "if-begin": "若",
    "if-condition-begin": "",
    "if-condition-end": "",
    "if-prefix": "",
    "if-infix==": "等於",
    "if-infix!=": "異於",
    "if-infix<": "小於",
    "if-infix>": "大於",
    "if-infix<=": "不大於",
    "if-infix>=": "不小於",
    "if-infixin": "含",
    "if-infixnotin": "不含",
    "if-then": "乎(、|)則",
    "if-else": "否則",
    "if-end": "條畢(。|)",
    "funcdef-begin": "術曰",
    "funcdef-name-begin": "",
    "funcdef-name-end": "",
    "funcdef-args-begin": "以",
    "funcdef-arg-separator": "與",
    "funcdef-args-end": "",
    "funcdef-noarg": "。",
    "funcdef-block": "",
    "funcdef-end": "術畢(。|)"
  },
  "yui": {
    "syntax": "Yui-Classic",
    "function-language": "ja",
    "whitespace": "[ \\t\\r　]",
    "whitespaces": "[ \\t\\r　]+",
    "linefeed": "[\\n]",
    "line-comment-begin": "[#＃]",
    "comment-begin": "",
    "comment-end": "",
    "indent": "  ",
    "null": "値なし|null",
    "boolean-true": "真|true",
    "boolean-false": "偽|false",
    "number-first-char": "[0-9]",
    "number-chars": "[0-9]*",
    "number-dot-char": "[\\.]",
    "name-first-char": "[A-Za-z_]",
    "name-chars": "[A-Za-z0-9_]*",
    "extra-name-begin": "「",
    "extra-name-end": "」",
    "string-begin": "\"",
    "string-end": "\"",
    "string-escape": "\\\\",
    "string-interpolation-begin": "\\{",
    "string-interpolation-end": "\\}",
    "string-content-end": "\\\\|\\{|\\\"",
    "!string-begin": "'|f\"",
    "array-begin": "\\[",
    "array-end": "\\]",
    "array-separator": "[,、，]",
    "object-begin": "\\{",
    "object-end": "\\}",
    "object-separator": "[,、，]",
    "key-value-separator": ":",
    "grouping-begin!": "\\(",
    "grouping-end!": "\\)",
    "length-begin": "\\|",
    "length-end": "\\|",
    "binary-infix+": "\\+",
    "binary-infix-": "-",
    "binary-infix*": "\\*",
    "binary-infix/": "/",
    "binary-infix%": "%",
    "binary-infix==": "==",
    "binary-infix!=": "!=",
    "binary-infix<=": "<=",
    "binary-infix>=": ">=",
    "binary-infix<": "<",
    "binary-infix>": ">",
    "unary-minus": "-",
    "array-indexer-suffix": "\\[",
    "array-indexer-end": "\\]",
    "property-length": "の大きさ",
    "funcapp-args-begin": "\\(",
    "funcapp-args-end": "\\)",
    "funcapp-separator": "[,、，]",
    "import-standard": "標準ライブラリを使う",
    "import-operator": "四則演算子を使う",
    "import-begin": "",
    "import-end": "を使う",
    "!block-begin": ":|：",
    "block-begin": "[\\{｛]",
    "block-end": "[\\}｝]",
    "block-line": "",
    "assignment-begin": "",
    "assignment-infix": "[=＝]",
    "assignment-end": "",
    "increment-begin": "",
    "increment-infix": "",
    "increment-end": "を増やす",
    "!increment-end": "\\+\\=|\\+\\+",
    "increment-lookahead": "増やす",
    "decrement-begin": "",
    "decrement-infix": "",
    "!decrement-end": "\\-\\=|\\-\\-",
    "decrement-end": "を減らす",
    "append-lookahead": "を追加する",
    "append-begin": "",
    "append-infix": "(の末尾)?に",
    "append-end": "を追加する",
    "append2-lookahead": "に追加する",
    "append2-begin": "",
    "append2-infix": "を",
    "append2-end": "に追加する",
    "print-begin": "",
    "print-end": "",
    "!break": "break",
    "break": "くり返しを抜ける",
    "pass": "何もしない",
    "!return-begin": "return",
    "return-begin": "",
    "return-end": "が[、]?答え",
    "return-none": "関数から抜ける",
    "repeat-begin": "",
    "repeat-times": "回[、]?",
    "!repeat-block": "繰り返す|くりかえす",
    "repeat-block": "くり返す",
    "repeat-end": "",
    "!if-begin": "if",
    "if-begin": "もし",
    "if-condition-begin": "",
    "if-condition-end": "",
    "if-prefix": "",
    "if-infix": "が",
    "!if-infix": "は|==|!=|<|<=|>|>=|＝|≦|≧|≠",
    "if-suffix!=": "以外",
    "!if-suffix!=": "でない",
    "if-suffix<": "より小さい",
    "if-suffix<=": "以下",
    "if-suffix>": "より大きい",
    "if-suffix>=": "以上",
    "if-suffixin": "のいずれか",
    "if-suffixnotin": "のいずれでもない",
    "if-then": "ならば[、]?",
    "if-else": "そうでなければ[、]?",
    "if-end": "",
    "funcdef-begin": "",
    "funcdef-name-begin": "",
    "funcdef-name-end": "[=＝]",
    "funcdef-args-begin": "入力",
    "funcdef-arg-separator": "[,、]",
    "funcdef-args-end": "",
    "funcdef-noarg": "入力なし",
    "funcdef-block": "に対し[て]?[、]?",
    "funcdef-end": ""
  },
  "zup": {
    "syntax": "cryptic zup",
    "description": "Zup is a programming language designed to be deliberately opaque to anyone unfamiliar with its specification. All keywords follow a strict CVC (Consonant-Vowel-Consonant) syllable structure, drawn from a constrained phoneme set that avoids common patterns found in natural languages — making the vocabulary impossible to guess by intuition alone.",
    "function-language": "emoji",
    "word-segmenter": " ",
    "comment-begin": "",
    "comment-end": "",
    "indent": "  ",
    "special-name-variable": "Kem\\s+({name_pattern})\\s+par",
    "null": "zup",
    "boolean-true": "vak",
    "boolean-false": "mep",
    "binary-infix+": "rug",
    "binary-infix-": "dap",
    "binary-infix*": "gev",
    "binary-infix/": "kum",
    "binary-infix%": "zen",
    "binary-infix==": "paz",
    "binary-infix!=": "nup",
    "binary-infix<=": "dur",
    "binary-infix>=": "pev",
    "binary-infix<": "dup",
    "binary-infix>": "pep",
    "binary-infixin": "kag",
    "property-length": "\\@kez",
    "import-standard": "Nav rem vaz",
    "import-begin": "Nav",
    "import-end": "",
    "block-begin": ":",
    "block-end": "",
    "assignment-begin": "Kem",
    "assignment-infix": "par",
    "assignment-end": "",
    "increment-begin": "Rav",
    "increment-end": "",
    "decrement-begin": "Zar",
    "decrement-end": "",
    "append-begin": "Mev",
    "append-infix": "naz",
    "append-end": "",
    "break": "Dez kup",
    "pass": "Mup nek",
    "print-begin": "",
    "print-end": "",
    "return-begin": "Dup vem",
    "return-end": "",
    "return-none": "Nag pag",
    "repeat-begin": "Mup dum",
    "repeat-times": "pag",
    "repeat-block": "",
    "repeat-end": "Dam mup",
    "if-begin": "Nev",
    "if-condition-begin": "",
    "if-condition-end": "",
    "if-prefix": "",
    "if-infix==": "paz",
    "if-infix!=": "nup",
    "if-infix<": "dup",
    "if-infix<=": "dur",
    "if-infix>": "pep",
    "if-infix>=": "pev",
    "if-infixin": "kag",
    "if-infixnotin": "nag",
    "if-then": "ger",
    "if-else": "Zum",
    "if-end": "Dam nev",
    "funcdef-begin": "Dum",
    "funcdef-name-begin": "",
    "funcdef-name-end": "",
    "funcdef-args-begin": "\\(",
    "funcdef-arg-separator": ",",
    "funcdef-args-end": "\\)",
    "funcdef-noarg": "",
    "funcdef-block": "",
    "funcdef-end": "Pam dum"
  },
});

/** 組み込み grammar 名の一覧 (ソート済み) */
export const SYNTAX_NAMES = Object.freeze(["ast","bridget","emoji","empty","jslike","nannan","pylike","sexpr","wenyan","yui","zup"]);

/** 名前から grammar を取得 (見つからなければ null を返す) */
export function getGrammar(name) {
  return GRAMMARS[name] ?? null;
}
